### ISSUE TITLE
Georgia: Martin Luther King Day

### ISSUE THREAD

**Issue by christophermosch** [ryanss/holidays.py#25]
Is it possible that Martin Luther King, Jr. Day is missing for Georgia?

```
for date,holiday in sorted(holidays.US(state='GA', years=range(2011,2014)).items()):
    print date, holiday
2010-12-31 New Year's Day (Observed)
2011-01-01 New Year's Day
2011-01-17 Robert E. Lee's Birthday
2011-04-25 Confederate Memorial Day
...
2012-01-01 New Year's Day
2012-01-02 New Year's Day (Observed)
2012-04-23 Confederate Memorial Day
...
2012-11-22 Thanksgiving
2012-11-23 Robert E. Lee's Birthday
2012-12-24 Washington's Birthday
2012-12-25 Christmas Day
2013-01-01 New Year's Day
2013-04-22 Confederate Memorial Day
2013-05-27 Memorial Day
...
```
(For brevity, I replaced some holidays with ... )

The code seems to associate Martin Luther King, Jr. Day with Robert E. Lee's Birthday prior to 2012.

```
        # Martin Luther King, Jr. Day
        if year >= 1986:
            name = "Martin Luther King, Jr. Day"
            if self.state == 'AL':
                name = "Robert E. Lee/Martin Luther King Birthday"
            elif self.state in ('AS', 'MS'):
                name = ("Dr. Martin Luther King Jr. "
                        "and Robert E. Lee's Birthdays")
            elif self.state in ('AZ', 'NH'):
                name = "Dr. Martin Luther King Jr./Civil Rights Day"
            elif self.state == 'GA' and year < 2012:
                name = "Robert E. Lee's Birthday"
            elif self.state == 'ID' and year >= 2006:
                name = "Martin Luther King, Jr. - Idaho Human Rights Day"
            if self.state != 'GA' or year < 2012:
                self[date(year, 1, 1) + rd(weekday=MO(+3))] = name
```

However, there are two issues. First, for Martin Luther King, Jr. Day to be included for Georgia after 2012, the last two lines should probably read
```
            if self.state != 'GA' or year >= 2012:
                self[date(year, 1, 1) + rd(weekday=MO(+3))] = name
```
Second, it seems that Martin Luther King, Jr. Day has been a state holiday in Georgia already prior to 2012. See https://web.archive.org/web/20110224172609/http://www.georgia.gov/00/channel_modifieddate/0,2096,4802_64437763,00.html, https://web.archive.org/web/20100304032739/http://www.georgia.gov/00/channel_modifieddate/0,2096,4802_64437763,00.html, and https://georgia.gov/popular-topic/observing-state-holidays.

Besides, the above links also seem to suggest that Lincoln's Birthday does not necessarily coincide with Martin Luther King, Jr. Day in Georgia.

**Comment by ryanss** [comment]
Originally the information regarding Martin Luther King, Jr. Day in Georgia came from here: http://www.timeanddate.com/holidays/us/martin-luther-king-day

It is clearly not correct. It looks like the federal holiday was adopted right away in 1986 and Robert E. Lee's Birthday was moved to the last Friday on or before Nov. 29th the same year.
