### ISSUE TITLE
Option for ignoring "unobserved" holidays

### ISSUE THREAD

**Issue by decibel** [ryanss/holidays.py#26]
It might be nice to allow for not adding holidays that are not going to be observed on their normal date. I'm guessing that this only happens when the actual holiday falls on a weekend so maybe it doesn't matter.

**Comment by ryanss** [comment]
To get a list like this you could just check if there's an "(Observed)" version of that holiday name and if there is not include it. Example:

```python
import holidays

us_holidays = holidays.US(years=2016)

# Print all holidays
for date, name in sorted(us_holidays.items()):
    print date, name

# Print only observed holidays
# skip holidays that fall on weekends that have an "(Observed)" version
for date, name in sorted(us_holidays.items()):
    if name + " (Observed)" not in us_holidays.values():
        print date, name
```
