### ISSUE TITLE
Ad-hoc UK bank holidays not included

### ISSUE THREAD

**Issue by SteveAyre** [ryanss/holidays.py#31]
The UK definitions are based on a calculation of when holidays would fall in a given year. However this fails to take into account additional bank holidays. For example 29 April 2011 was a bank holiday but the library reports that it was not.

**Comment by ryanss** [comment]
Thanks. Are there any other one-off holidays like this you are aware of?

**Comment by SteveAyre** [comment]
There's a list of a few in the Notes section of:
https://en.wikipedia.org/wiki/Public_holidays_in_the_United_Kingdom#England.2C_Northern_Ireland_and_Wales.
