### ISSUE TITLE
Holiday object doesn't generate holidays until __contains__() ran

### ISSUE THREAD

**Issue by ryancurrah** [ryanss/holidays.py#33]
As shown below holidays won't appear in the object until I check if a date is in the holiday object. 

```
Python 2.7.5 (default, Oct 11 2015, 17:47:16) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import holidays
>>> print holidays.__version__
0.5
>>> h = holidays.UnitedStates()
>>> h
{}
>>> datetime.datetime.now() in h
False
>>> h
{datetime.date(2016, 11, 24): 'Thanksgiving', datetime.date(2016, 2, 15): "Washington's Birthday", datetime.date(2016, 7, 4): 'Independence Day', datetime.date(2016, 9, 5): 'Labor Day', datetime.date(2016, 12, 25): 'Christmas Day', datetime.date(2016, 1, 1): "New Year's Day", datetime.date(2016, 10, 10): 'Columbus Day', datetime.date(2016, 1, 18): 'Martin Luther King, Jr. Day', datetime.date(2016, 12, 26): 'Christmas Day (Observed)', datetime.date(2016, 11, 11): 'Veterans Day', datetime.date(2016, 5, 30): 'Memorial Day'}
```

**Comment by ryanss** [comment]
This is on purpose. There is an optional `years` parameter you can use to force it to generate specific years before checking any dates.

```python
>>> h = holidays.US(years=2016)
>>> h
{datetime.date(2016, 11, 24): 'Thanksgiving', datetime.date(2016, 2, 15): "Washington's Birthday", datetime.date(2016, 7, 4): 'Independence Day', datetime.date(2016, 9, 5): 'Labor Day', datetime.date(2016, 12, 25): 'Christmas Day', datetime.date(2016, 1, 1): "New Year's Day", datetime.date(2016, 10, 10): 'Columbus Day', datetime.date(2016, 1, 18): 'Martin Luther King, Jr. Day', datetime.date(2016, 12, 26): 'Christmas Day (Observed)', datetime.date(2016, 11, 11): 'Veterans Day', datetime.date(2016, 5, 30): 'Memorial Day'}

# or multiple years
>>> h = holidays.US(years[2015, 2016, 2017])
```

One option would be to default the `years` argument to the current year but my thinking was as follows:
At the time of creating object `h` it doesn't know what year(s) you are going to be working with and you wouldn't want to waste cpu cycles generating the current year if you plan on working with another year, or perhaps you initialize the holiday object and never need to use it.

If you think this is not the ideal default I'm open to be persuaded differently.

**Comment by ryancurrah** [comment]
@ryanss that makes sense. Appreciate your response. No I think your reasoning is valid. Mind if create a Pull Request that updates the docs with an example of initiating the object with the years? As I'm using it to get a list of holidays to exclude from dateutil rrule set.

**Comment by ryanss** [comment]
Sure, better documentation is always helpful.

You may be interested in another one of my projects https://github.com/ryanss/bdateutil.

The main feature is adding a new `bday` option to `relativedelta` and `BDAILY` to `rrule`. The last example in the top _Example Usage_ section might be what you're looking for.

```python
import holidays
from bdateutil import rrule, BDAILY
from datetime import date

for dt in rrule(BDAILY, count=10, dtstart=date(2015, 12, 23), holidays=holidays.US()):
    print dt
```

Unfortunately, the `holidays` keyword is only available in the master branch, not the latest release v0.1, so you would have to clone the repository and `python setup.py install` instead of installing using easy_install or pip. I will be releasing v0.2 to PyPI sometime in the next week.
