### ISSUE TITLE
US Presidential Inauguration Day

### ISSUE THREAD

**Issue by spatovich** [ryanss/holidays.py#6]
Is there a reason why you didn't include the US Presidential Inauguration Day:
http://www.opm.gov/policy-data-oversight/pay-leave/pay-administration/fact-sheets/holidays-work-schedules-and-pay

**Comment by ryanss** [comment]
From your link it looks like a very small percentage of the United States gets this day as a holiday so leaving it off the list of default US holidays is the correct thing to do. In the future I plan on adding an optional `state` parameter that will allow state-specific holidays like Presidential Inauguration Day, Election Day, Good Friday, etc.

At this time, if you need holidays that differ from the default holidays, it is very easy to subclass `holidays.UnitedStates` to modify the holidays:

```python
from datetime import date
from dateutil.relativedelta import relative delta

import holidays

class MyUSHolidays(holidays.UnitedStates):
    def _populate(self, year):
        # Populate the holiday list with the default US holidays
        holidays.UnitedStates._populate(self, year)
        # Add Presidential Inauguration Day
        # Occurs every four years starting in 1937
        if (year - 1937) % 4 == 0:
            # If Jan 20 is a Sunday holiday falls on Jan 21
            if date(year, 1, 20).weekday() != 6:
                self[date(year, 1, 20)] = "Presidential Inauguration Day"
            else:
                self[date(year, 1, 21)] = "Presidential Inauguration Day"

print date(2013, 1, 21) in MyUSHolidays()
```

**Comment by spatovich** [comment]
That makes sense. Thank you for creating this module.
